# theme: jekyll-theme-minimal
# theme: tale
remote_theme: chesterhow/tale
permalink:  /:year-:month-:day/:title
paginate:   5
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  
markdown: kramdown
title: Miry's notes
description: Collection of all my articles posted
twitter_username: miry_sof
github_username:  miry

defaults:
  - scope:
      path: ""
    values:
      layout: post
