theme: jekyll-theme-minimal
# theme: minima
title: Miry's articles
description: Collection of all articles posted
twitter_username: miry_sof
github_username:  miry

defaults:
- scope:
    path: ""
  values:
    layout: default
